# systemd-boot entry for Flavos OS
# NOTA: PARTUUID_ROOT será substituído em tempo de build pelo script 03.
title   Flavos OS
linux   /vmlinuz
initrd  /initrd.img
options root=PARTUUID=__PARTUUID_ROOT__ rw quiet
