[Journal]
# Força persistência do journald em disco (/var/log/journal)
Storage=persistent
# Trava o consumo em 50 Megabytes para não inchar o SO
SystemMaxUse=50M
# Garante sync no disco logando falhas perfeitamente em crash hard
SyncIntervalSec=1m
