[general]
fontname=Inter 11
bgcolor=#12141A
fgcolor=#EDEDED
palette_color_0=#1E212B
palette_color_1=#f87171
palette_color_2=#4ade80
palette_color_3=#facc15
palette_color_4=#3B82F6
palette_color_5=#c084fc
palette_color_6=#2dd4bf
palette_color_7=#eaecf0
palette_color_8=#3A3F50
palette_color_9=#fca5a5
palette_color_10=#86efac
palette_color_11=#fef08a
palette_color_12=#60A5FA
palette_color_13=#d8b4fe
palette_color_14=#5eead4
palette_color_15=#ffffff
scrollback=1000
scrollbar=false
cursorblinks=true
cursorline=false
color_preset=Flavos
hide_menubar=true
disallow_bold=false
tab_position=bottom
